# Generated by Django 3.2.8 on 2021-11-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_auto_20211123_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='displayPicture',
            field=models.ImageField(blank=True, null=True, upload_to='media/dp'),
        ),
    ]
