# Generated by Django 3.2.8 on 2022-03-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_auto_20220301_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='linkedln_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
