# Generated by Django 3.2.8 on 2022-07-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_alter_userprofile_displaypicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bvn',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
