# Generated by Django 3.2.8 on 2022-01-18 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_userprofile_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subSkills',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(max_length=255),
        ),
    ]
