# Generated by Django 3.2.8 on 2022-02-03 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_proposal_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='job.jobpost'),
        ),
    ]
