# Generated by Django 3.2.8 on 2022-01-23 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobpost_skills_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='skills_required',
            new_name='sub_category',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='budgete_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
