# Generated by Django 3.2.8 on 2022-01-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20220123_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='budgete_type',
            new_name='budget_type',
        ),
    ]
